# Generated by Django 3.2.9 on 2021-12-02 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Name of the csv file')),
                ('file_path', models.FileField(upload_to='uploads/', verbose_name='Imagen principal')),
                ('category', models.CharField(choices=[('', 'Please select an option'), ('Classification', 'Classification'), ('Prediction', 'Prediction')], max_length=255)),
                ('id_column', models.CharField(blank=True, help_text='*Optional', max_length=55)),
                ('target_column', models.CharField(help_text='*Opcional', max_length=55)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registers',
            },
        ),
    ]
